language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t vdrozdovskyi/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vdrozdovskyi/docker-react npm run test -- --coverage